name: bjs_food_runs
description: BJ's food run tracker with day planning, gamification, and admin controls
publish_to: "none"
version: 1.3.0+130

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.66.2
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  confetti: ^0.7.0
  table_calendar: ^3.1.2
  flutter_native_splash: ^2.4.6
  image_picker: ^1.0.7
  path_provider: ^2.1.5
  uuid: ^4.5.1
  intl: ^0.20.2

flutter:
  uses-material-design: true
  assets:
  - assets/splash.png
  - assets/foodrunner.png
  - assets/avatars/