name: bjs_food_runs
description: BJ's food run tracker with day planning, gamification, and admin controls
publish_to: "none"
version: 1.3.0+130

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  confetti: ^0.7.0
  table_calendar: ^3.1.2

flutter:
  uses-material-design: true
